changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🧰 Maintenance
      labels:
        - chore
        - dependencies
    - title: Other Changes
      labels:
        - "*"

template: |
  This release supports the following ASIC models: BM1366, BM1368, BM1397, BM1370

  ## What's Changed
  $CHANGES